### ISSUE TITLE
source code request

### ISSUE THREAD

**Issue by TsengDuncan** [MiZhenxing/Switch-NeRF#1]
I was working on the research of NeRF. I've noticed your submission on 2023 ICLR and it is a great honour for me to read your article, Switch-NeRF: Learning Scene Decomposition with Mixture of Experts for Large-scale Neural Radiance Fields. It is impressive that you bring MoE into the application of NeRF. The work makes me refreshed and I want to induct it into other fields. I am very interested in your research and want to further explore the research. But unfortunately, I can not access the codes on Github URL you leave when I try to implement your algorithm. Could you please upload the source code of your project?

**Comment by MiZhenxing** [comment]
Hi, we released a beta version. Please note that there are still some bugs and the documentation is currently not complete. We will continue improving the code and adding necessary documentation and trained models. It will take about one week. Thanks for you interests in our method.
