### ISSUE TITLE
The ckpt provided on the building dataset yielded weak results

### ISSUE THREAD

**Issue by WeiGuaa** [MiZhenxing/Switch-NeRF#10]
I downloaded the provided ckpt of building,then ran the following command：
`CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --use_env --master_port=12345 --nproc_per_node=1 -m switch_nerf.eval_image --config=switch_nerf/configs/switch_nerf/building.yaml --use_moe --exp_name=output/building-pixsfm/ --dataset_path=data/building-pixsfm/ --i_print=1000 --moe_expert_type=seqexperts --model_chunk_size=131072 --ckpt_path=output/building-pixsfm/ckpt/building.pt --expertmlp2seqexperts --use_moe_external_gate --use_gate_input_norm`

The evaluation indicators obtained are as follows:
`INFO:root:Average val/time: 44.57523021697998
2023-11-29 19:59:28,001 root INFO: Average val/time: 44.57523021697998
INFO:root:Average val/memory: 5856.643969726562
2023-11-29 19:59:28,001 root INFO: Average val/memory: 5856.643969726562
INFO:root:Average val/psnr: 21.543164134025574
2023-11-29 19:59:28,001 root INFO: Average val/psnr: 21.543164134025574
INFO:root:Average val/ssim: 0.5792561799287796
2023-11-29 19:59:28,001 root INFO: Average val/ssim: 0.5792561799287796
INFO:root:Average val/lpips/vgg: 0.47358196824789045
2023-11-29 19:59:28,001 root INFO: Average val/lpips/vgg: 0.47358196824789045
INFO:root:Average val/lpips/alex: 0.39700327515602113
2023-11-29 19:59:28,001 root INFO: Average val/lpips/alex: 0.39700327515602113
INFO:root:Average val/lpips/squeeze: 0.29448841512203217
2023-11-29 19:59:28,001 root INFO: Average val/lpips/squeeze: 0.29448841512203217`

These results are consistent with the results presented in the paper on the building data.However, when I looked at the rendered image, I felt that it was not very good and there were some artifacts and blurring.
![0_gt](https://github.com/MiZhenxing/Switch-NeRF/assets/115336829/3b39d9f5-8e6f-4bb9-98d7-47a6903fabf0)
![0_pred](https://github.com/MiZhenxing/Switch-NeRF/assets/115336829/646feed2-1b88-46de-9c55-926d02b330b3)
![14_gt](https://github.com/MiZhenxing/Switch-NeRF/assets/115336829/9a666af9-ebc9-4e68-998e-fcf0d90e3c7e)
![14_pred](https://github.com/MiZhenxing/Switch-NeRF/assets/115336829/5b74dab9-3c16-436c-ac1d-1e5db72fb242)

Is this caused by parameter settings? Thank you for your help.

**Comment by MiZhenxing** [comment]
Hi, this is not related to the parameter settings. The large-scale scene is challenging with less overlapping among images, so the quality of rendering images is not as high as that of the small-scale scenes.

**Comment by WeiGuaa** [comment]
> Hi, this is not related to the parameter settings. The large-scale scene is challenging with less overlapping among images, so the quality of rendering images is not as high as that of the small-scale scenes.

Thank you for your reply, I get it.
