### ISSUE TITLE
About render rate

### ISSUE THREAD

**Issue by YHJCTR** [MiZhenxing/Switch-NeRF#14]
Hello author, thank you for opening source the code for this work. When I tested the model, I found that it went through a round of iterations for about 113s, with a total of 20 rounds. May I ask if this 113s is the time used to render a picture? My device is RTX 3090

**Comment by MiZhenxing** [comment]
Hi, the 113s typically contain the rendering time and the time for computing metrics. lpips needs evaluating the VGG model for 3 times.

**Comment by YHJCTR** [comment]
Thanks for your reply
