### ISSUE TITLE
tutel installation error

### ISSUE THREAD

**Issue by zhaojiancheng007** [MiZhenxing/Switch-NeRF#2]
I cannot build tutel correctly, did you ever met the problem that cannot find 'tutel_custom_kernel'？

**Comment by MiZhenxing** [comment]
Hi, "the problem that cannot find 'tutel_custom_kernel'" means you did not compile the cuda extension of Tutel. You can follow the instructions in Tutel and our [install_tutel.md](https://github.com/MiZhenxing/Switch-NeRF/blob/main/install_tutel.md) for detail.
