### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by gjgjgjfff** [MiZhenxing/Switch-NeRF#8]
[E ProcessGroupNCCL.cpp:587] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801171 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:587] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801172 milliseconds before timing out.

Why is this? 

This seems to indicate that a timeout error occurred while performing some kind of parallel computing task. Specifically, when using NCCL (NVIDIA Collective Communications Library) for communication, a certain operation took longer than the set threshold (1800000 milliseconds, or 30 minutes) and was therefore interrupted.

Have you ever encountered such a problem? Can you give me some solutions?

**Comment by MiZhenxing** [comment]
Hi, you may use "--set_timeout" flag. This will extend the time limit to 1 day.
