### ISSUE TITLE
Can't run on Bungee-NeRF scenes

### ISSUE THREAD

**Issue by bhiaibogf** [MiZhenxing/Switch-NeRF#9]
Hi, I followed readme and tried [this example code](https://github.com/MiZhenxing/Switch-NeRF#bungee-nerf-scenes), but got an error:  'Error while finding module specification for 'mega_nerf.train_nerf_moe' (ModuleNotFoundError: No module named 'mega_nerf')'. And I didn't find the mega_nerf directory nor train_nerf_moe.py file. Are there any files missed?

**Comment by MiZhenxing** [comment]
Hi, thanks for your question. I updated the readme. You can use switch_nerf.train_nerf_moe to run the program.
